sudo: required
services:
  - docker

before_install:
  - docker build -t eddwiin/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run eddwiin/react-test npm test -- --coverage

after_success:
  - docker build -t eddwiin/multi-client ./client
  - docker build -t eddwiin/multi-nginx ./nginx
  - docker build -t eddwiin/multi-server ./server
  - docker build -t eddwiin/multi-worker ./worker

  # Log in to the Docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #take those images and push them to Docker hub
  - docker push eddwiin/multi-client
  - docker push eddwiin/multi-nginx
  - docker push eddwiin/multi-server
  - docker push eddwiin/multi-worker

